name: "Go Test and Release"

on:
#  TODO: Change this to release
  push:
    branches: [ main ]
  release:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        go-version: [ 1.19 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
